services:
  - type: web
    name: kari-teeri
    runtime: node
    plan: free
    numInstances: 1
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
