services:
  - type: web
    name: kari-teeri
    runtime: node
    plan: free
    numInstances: 1
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production npm run start
    healthCheckPath: /health
